### ISSUE TITLE
Why not CH552G

### ISSUE THREAD

**Issue by xlxlxll** [hackpascal/ufprog#1]
为啥不加上支持ch552g呢，读取速度更快啊！而且demo板价格也不贵。
期待！

**Comment by hackpascal** [comment]
你确定？ch552的usb只有全速模式，最高就1MB/s

**Comment by xlxlxll** [comment]
CH552手册
USB：内嵌USB控制器和USB收发器，支持USB-Device设备模式，支持USB type-C主从检测，支持USB 2.0全速12Mbps或者低速1.5Mbps。支持最大64字节数据包，内置FIFO，支持DMA。

支持USB 2.0全速12Mbps

**Comment by hackpascal** [comment]
12Mbps是bit/s。折算下来是12/8=1.5，就是我说的基本上就1MB/s

**Comment by xlxlxll** [comment]
应该和ch341速度相当吧

**Comment by hackpascal** [comment]
这就不能直接比较。这个是通用MCU，需要自己开发固件来实现SPI到USB之间的数据交互的。SPI效率完全取决于开发者的水平。

**Comment by xlxlxll** [comment]
minpro编程器就是基于552的，我用着速度还可以，挺快的
