### ISSUE TITLE
"Package 'hidapi-libusb', required by 'virtual:world', not found" Vs "libhidapi-libusb0 is already the newest version (0.14.0-1build1)"

### ISSUE THREAD

**Issue by minkione** [hackpascal/ufprog#10]
**OS:** Ubuntu 24.04 LTS
**Commands ran so far:**
```
cd ufprog   
mkdir build-dir  
cd build-dir/  
cmake ..
```
**The error:**
```
-- Checking for module 'hidapi-libusb'
--   Package 'hidapi-libusb', required by 'virtual:world', not found
CMake Error at /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - hidapi-libusb

Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:841 (_pkg_check_modules_internal)
  controller/wch/CMakeLists.txt:17 (pkg_check_modules)
```

**However hidapi is already isntalled through aptitude:**
`libhidapi-libusb0 is already the newest version (0.14.0-1build1).`

**Comment by hackpascal** [comment]
Did you install libhidapi-dev?

**Comment by minkione** [comment]
Nope! That I one I missed.
Xie Xie!

**Comment by minkione** [comment]
Quick question... how to build it for Windows? 😊

**Comment by hackpascal** [comment]
Although ufprog supports MSVC, I recommend building it with MSYS2/GCC.

You need to setup MSYS2 environment first:
https://www.msys2.org/
https://www.msys2.org/docs/installer/
https://www.msys2.org/docs/updating/

Install `mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-libusb mingw-w64-ucrt-x86_64-hidapi mingw-w64-ucrt-x86_64-json-c mingw-w64-ucrt-x86_64-make git`

Clone the source and build as what you've done in linux.

Add -DBUILD_PORTABLE=ON to cmake if you want to build a portable version.

I personally uses mingw32-make for building. You can also use ninja by installing `mingw-w64-ucrt-x86_64-ninja`

```
git clone https://github.com/hackpascal/ufprog
cd ufprog
mkdir build
cd build
cmake .. -DBUILD_PORTABLE=ON -G "MinGW Makefiles"
mingw32-make -j24
mingw32-make install DESTDIR=~/ufprog-install
```

Remember to copy `libgcc_s_seh-1.dll libhidapi-0.dll libjson-c-5.dll libusb-1.0.dll libwinpthread-1.dll` to program's directory
