### ISSUE TITLE
Please add FT232H in next release

### ISSUE THREAD

**Issue by chrisdartw** [hackpascal/ufprog#2]
Here provides JSON : ft232h.json & ft232h-libusb.json
{
	"driver": "mpsse-d2xx",
	"if_type": [ "spi", "i2c" ],
	"config": {
		"match": [
			{
				"type": "description",
				"value": "Single RS232-HS"
			}
		],
		"spi": {
		}
	}
}
{
	"driver": "mpsse-libusb",
	"if_type": [ "spi", "i2c" ],
	"config": {
		"match": [
			{
				"vid": "0403",
				"pid": "6014"
			}
		],
		"spi": {
		}
	}
}

Here provides log of test.

ufsnortest.exe dev=FT232H  all

Universal flash programmer for SPI-NOR 1.0 [Portable]
Flash Test Utility
Author: Weijie Gao <hackpascal@gmail.com>

Loaded interface driver FTDI MPSSE (D2XX) 1.0
MPSSE-D2XX: Opened device with 'description': 'Single RS232-HS'
MPSSE-D2XX: Chip is FT232H
Opened interface device 'FT232H' using driver 'mpsse-d2xx'

Manufacturer:       Winbond
Part:               W25Q64JV
Capacity:           8MB
Clock:              30MHz

[ Flash regular Read/Write/Erase test ]

1. Erase whole flash
Erasing flash at 0x0, size 0x800000 ...
[========================================================================] 100%
Time used: 23.35s, speed: 350.81KB/s
Succeeded

2. Verifying if all data bytes are FFh after erase
Reading from flash at 0x0, size 0x800000 ...
[========================================================================] 100%
Time used: 2.69s, speed: 2.97MB/s
Succeeded

3. Writing random pattern and verify
Writing to flash at 0x0, size 0x800000 ...
[========================================================================] 100%
Time used: 196.61s, speed: 41.67KB/s
Succeeded

Verifying flash data at 0x0, size 0x800000 ...
[========================================================================] 100%
Time used: 2.70s, speed: 2.96MB/s
Succeeded

4. Writing zero data and verify
Writing to flash at 0x0, size 0x800000 ...
[========================================================================] 100%
Time used: 196.60s, speed: 41.67KB/s
Succeeded

Verifying flash data at 0x0, size 0x800000 ...
[========================================================================] 100%
Time used: 2.70s, speed: 2.96MB/s
Succeeded

R/W test passed

[ Flash OTP Read/Write/Erase test ]

Testing OTP region 1:
    1. Erase whole OTP region
       Succeeded
    2. Verify if all data bytes are FFh after erase
       Succeeded
    3. Write random pattern
       Succeeded
    4. Verify pattern
       Succeeded
OTP region 1 test passed

Testing OTP region 2:
    1. Erase whole OTP region
       Succeeded
    2. Verify if all data bytes are FFh after erase
       Succeeded
    3. Write random pattern
       Succeeded
    4. Verify pattern
       Succeeded
OTP region 2 test passed

Testing OTP region 3:
    1. Erase whole OTP region
       Succeeded
    2. Verify if all data bytes are FFh after erase
       Succeeded
    3. Write random pattern
       Succeeded
    4. Verify pattern
       Succeeded
OTP region 3 test passed

[ Flash Write-protect test ]

Testing ALL
    Passed
Testing 7E0000h - 7FFFFFh
    Passed
Testing 7C0000h - 7FFFFFh
    Passed
Testing 780000h - 7FFFFFh
    Passed
Testing 700000h - 7FFFFFh
    Passed
Testing 600000h - 7FFFFFh
    Passed
Testing 400000h - 7FFFFFh
    Passed
Testing 000000h - 01FFFFh
    Passed
Testing 000000h - 03FFFFh
    Passed
Testing 000000h - 07FFFFh
    Passed
Testing 000000h - 0FFFFFh
    Passed
Testing 000000h - 1FFFFFh
    Passed
Testing 000000h - 3FFFFFh
    Passed
Testing 7FF000h - 7FFFFFh
    Passed
Testing 7FE000h - 7FFFFFh
    Passed
Testing 7FC000h - 7FFFFFh
    Passed
Testing 7F8000h - 7FFFFFh
    Passed
Testing 000000h - 000FFFh
    Passed
Testing 000000h - 001FFFh
    Passed
Testing 000000h - 003FFFh
    Passed
Testing 000000h - 007FFFh
    Passed
Testing 020000h - 7FFFFFh
    Passed
Testing 040000h - 7FFFFFh
    Passed
Testing 080000h - 7FFFFFh
    Passed
Testing 100000h - 7FFFFFh
    Passed
Testing 200000h - 7FFFFFh
    Passed
Testing 000000h - 7DFFFFh
    Passed
Testing 000000h - 7BFFFFh
    Passed
Testing 000000h - 77FFFFh
    Passed
Testing 000000h - 6FFFFFh
    Passed
Testing 000000h - 5FFFFFh
    Passed
Testing 001000h - 7FFFFFh
    Passed
Testing 002000h - 7FFFFFh
    Passed
Testing 004000h - 7FFFFFh
    Passed
Testing 008000h - 7FFFFFh
    Passed
Testing 000000h - 7FEFFFh
    Passed
Testing 000000h - 7FDFFFh
    Passed
Testing 000000h - 7FBFFFh
    Passed
Testing 000000h - 7F7FFFh
    Passed

[ Flash test finished ]

**Comment by hackpascal** [comment]
Added in https://github.com/hackpascal/ufprog/commit/d60a0eb4310090b96787a40b5baea04ba90f249f
