### ISSUE TITLE
How to add W25H256JV to spi-nor-ids.json ?

### ISSUE THREAD

**Issue by chrisdartw** [hackpascal/ufprog#4]
Can you provide an example for W25H256JV in spi-nor-ids.json?

`
Manufacturer:       Winbond
Part:               JESD216A SFDP compatible
Capacity:           32MB
Clock:              30MHz

JEDEC ID:           EF 90 19
Block/Sector size:  64KB 4KB
Page size:          256B
Max speed:          30MHz
Protocol:           SPI
Read I/O:           1-1-1
Write I/O:          1-1-1
OTP:                3 * 256B

Manufacturer:       Winbond
Part:               JESD216A SFDP compatible
Capacity:           32MB
Clock:              30MHz

00000000: 53 46 44 50  05 01 00 ff  00 05 01 10  80 00 00 ff  SFDP............
00000010: ff ff ff ff  ff ff ff ff  ff ff ff ff  ff ff ff ff  ................
00000020: ff ff ff ff  ff ff ff ff  ff ff ff ff  ff ff ff ff  ................
00000030: ff ff ff ff  ff ff ff ff  ff ff ff ff  ff ff ff ff  ................
00000040: ff ff ff ff  ff ff ff ff  ff ff ff ff  ff ff ff ff  ................
00000050: ff ff ff ff  ff ff ff ff  ff ff ff ff  ff ff ff ff  ................
00000060: ff ff ff ff  ff ff ff ff  ff ff ff ff  ff ff ff ff  ................
00000070: ff ff ff ff  ff ff ff ff  ff ff ff ff  ff ff ff ff  ................
00000080: e5 20 fb ff  ff ff ff 0f  44 eb 08 6b  08 3b 42 bb  . ......D..k.;B.
00000090: fe ff ff ff  ff ff 00 00  ff ff 40 eb  0c 20 0f 52  ..........@.. .R
000000a0: 10 d8 00 00  36 02 a6 00  82 ea 14 d3  e9 63 76 33  ....6........cv3
000000b0: 7a 75 7a 75  f7 a2 d5 5c  19 f7 4d ff  e9 70 f9 a5  zuzu...\..M..p..
`

**Comment by hackpascal** [comment]
https://github.com/hackpascal/ufprog/blob/master/static/examples/spi-nor-ids.json

**Comment by chrisdartw** [comment]
I applied static/examples/spi-nor-ids.json, some changes happened

from:
Manufacturer:       Winbond
Part:               JESD216A SFDP compatible
Capacity:           32MB
Clock:              30MHz

change to:
Manufacturer:       (null)
Part:               JESD216A SFDP compatible
Capacity:           32MB
Clock:              30MHz

I guess there are some problems in this example.

**Comment by hackpascal** [comment]
Can you provide me your modification.

**Comment by chrisdartw** [comment]
The same  [file](https://pastebin.com/raw/r7AwDk3x)  has different behaviors for different versions.

ufprog-win64-mingw-msvcrt-1.0::
Manufacturer:       Winbond
Part:               W25H256JV-copy
Capacity:           32MB
Clock:              30MHz
JEDEC ID:           EF 90 19


ufprog-win64-mingw-msvcrt-2023-09-14:::
Manufacturer:       (null)
Part:               JESD216A SFDP compatible
Capacity:           32MB
Clock:              30MHz
JEDEC ID:           EF 90 19

**Comment by hackpascal** [comment]
Oh. I've modified some code about the vendor list. I'll check this.

**Comment by hackpascal** [comment]
I've fixed a bug in processing spi-nor-ids.json

https://github.com/hackpascal/ufprog/commit/07578c0423ec6f38fc95694fecf698e50b819f7b
